// examples/vue/src/App.vue
<script setup lang="ts">
import { onMounted, shallowRef } from "vue";
import NearWalletSelector from "near-wallet-selector";

import getConfig from "./config";
import Content from "./components/Content.vue";

const selector = shallowRef<NearWalletSelector>();

onMounted(async () => {
  const nearConfig = getConfig("testnet");

  const nearWalletSelector = new NearWalletSelector({
    wallets: ["near-wallet", "sender-wallet", "ledger-wallet"],
    networkId: "testnet",
    theme: "light",
    contract: {
      accountId: nearConfig.contractName,
    },
    walletSelectorUI: {
      description: "Please select a wallet to connect to this dApp:",
      explanation: [
        "Wallets are used to send, receive, and store digital assets.",
        "There are different types of wallets. They can be an extension",
        "added to your browser, a hardware device plugged into your",
        "computer, web-based, or as an app on your phone.",
      ].join(" "),
    },
  });

  await nearWalletSelector.init();

  selector.value = nearWalletSelector;
});
</script>

<template>
  <h1>NEAR Guest Book</h1>
  <Content v-if="!!selector" :selector="selector" />
</template>

// examples/angular/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import NearWalletSelector from "near-wallet-selector";
import getConfig from "../config";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent implements OnInit {
  selector: NearWalletSelector;

  async ngOnInit() {
    await this.initialize();
  }

  async initialize() {
    const nearConfig = getConfig("testnet");

    const nearWalletSelector = new NearWalletSelector({
      wallets: ["near-wallet", "sender-wallet", "ledger-wallet"],
      networkId: "testnet",
      theme: "light",
      contract: {
        accountId: nearConfig.contractName,
      },
      walletSelectorUI: {
        description: "Please select a wallet to connect to this dApp:",
        explanation: [
          "Wallets are used to send, receive, and store digital assets.",
          "There are different types of wallets. They can be an extension",
          "added to your browser, a hardware device plugged into your",
          "computer, web-based, or as an app on your phone.",
        ].join(" "),
      },
    });
    await nearWalletSelector.init();

    this.selector = nearWalletSelector;
  }
}

<main>
  <div class="title-container">
    <h1>{{showImport ? "Export Account" : "NEAR Guest Book"}}</h1>
    <button (click)="showImport = !showImport" >
      {{showImport ? "Back to Log in" : "Try Export Account"}}
    </button>
  </div>
  <near-wallet-selector-wallet-selector *ngIf="!showImport"></near-wallet-selector-wallet-selector>
  <near-wallet-selector-wallet-selector-export *ngIf="showImport"></near-wallet-selector-wallet-selector-export>
</main>
