// example/src/components/Messages.jsx
import React from "react";
import PropTypes from "prop-types";

export default function Messages({ messages }) {
  return (
    <>
      <h2>Messages</h2>
      {messages.map((message, i) => (
        // TODO: format as cards, add timestamp
        <p key={i} className={message.premium ? "is-premium" : ""}>
          <strong>{message.sender}</strong>:<br />
          {message.text}
        </p>
      ))}
    </>
  );
}

Messages.propTypes = {
  messages: PropTypes.array,
};

// examples/vue/src/components/Messages.vue
<script setup lang="ts">
import { Message } from "../interfaces";

defineProps<{
  messages: Array<Message>;
}>()
</script>

<template>
  <h2>Messages</h2>
  <!-- format as cards, add timestamp -->
  <p v-for="message in messages" class="{{ message.premium ? 'is-premium' : '' }}">
    <strong>{{ message.sender }}</strong>:<br />
    {{ message.text }}
  </p>
</template>
