// examples/vue/src/App.vue
<script setup lang="ts">
import { onMounted, shallowRef } from "vue";
import NearWalletSelector from "near-wallet-selector";

import getConfig from "./config";
import Content from "./components/Content.vue";

const selector = shallowRef<NearWalletSelector>();

onMounted(async () => {
  const nearConfig = getConfig("testnet");

  const nearWalletSelector = new NearWalletSelector({
    wallets: ["near-wallet", "sender-wallet", "ledger-wallet"],
    networkId: "testnet",
    theme: "light",
    contract: {
      accountId: nearConfig.contractName,
    },
    walletSelectorUI: {
      description: "Please select a wallet to connect to this dApp:",
      explanation: [
        "Wallets are used to send, receive, and store digital assets.",
        "There are different types of wallets. They can be an extension",
        "added to your browser, a hardware device plugged into your",
        "computer, web-based, or as an app on your phone.",
      ].join(" "),
    },
  });

  await nearWalletSelector.init();

  selector.value = nearWalletSelector;
});
</script>

<template>
  <h1>NEAR Guest Book</h1>
  <Content v-if="!!selector" :selector="selector" />
</template>

// examples/react/src/App.tsx
import React, { useState, useEffect, Fragment, useRef } from "react";
import NearWalletSelector from "near-wallet-selector";

import getConfig from "./config";
import Content from "./components/Content";

const App: React.FC = () => {
  const [loaded, setLoaded] = useState(false);
  const selectorRef = useRef<NearWalletSelector>();

  useEffect(() => {
    const nearConfig = getConfig("testnet");

    const selector = new NearWalletSelector({
      wallets: ["near-wallet", "sender-wallet", "ledger-wallet"],
      networkId: nearConfig.networkId,
      contract: { contractId: nearConfig.contractName },
    });

    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore-next-line
    window.selector = selector;

    selector.init().then(() => {
      selectorRef.current = selector;
      setLoaded(true);
    });

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!loaded) {
    return null;
  }

  return (
    <Fragment>
      <h1>NEAR Guest Book</h1>
      {/* eslint-disable-next-line @typescript-eslint/no-non-null-assertion */}
      <Content selector={selectorRef.current!} />
    </Fragment>
  );
};

export default App;
