// examples/angular/src/app/components/form/form.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import { AccountInfo } from "near-wallet-selector/lib/esm/wallets/Wallet";
import Big from "big.js";

export interface NewMessage {
  donation: string;
  message: string;
}

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss']
})
export class FormComponent implements OnInit {
  @Input() account: AccountInfo;
  @Output() onAddMessage: EventEmitter<NewMessage> = new EventEmitter();
  donation  = "0";
  message = '';
  maxValue: string;

  ngOnInit(): void {
    this.maxValue = Big(this.account.balance).div(10 ** 24).toString();
  }

  onSubmit () {
    const data: NewMessage = {
      message: this.message.toString(),
      donation: this.donation.toString()
    }
    this.onAddMessage.emit(data)
  }
}

<form (ngSubmit)="onSubmit()">
  <fieldset id="fieldset">
    <p>Sign the guest book, {{ account.accountId }}!</p>
    <p class="highlight">
      <label for="message">Message:</label>
      <input autoComplete="off" autoFocus id="message" required [(ngModel)]="message" name="message"/>
    </p>
    <p>
      <label for="donation">Donation (optional):</label>
      <input
        autoComplete="off"
        [defaultValue]="'0'"
        id="donation"
        max="{{ maxValue }}"
        min="0"
        step="0.01"
        type="number"
        [(ngModel)]="donation"
        name="donation"
      />
      <span title="NEAR Tokens">Ⓝ</span>
    </p>
    <button type="submit">Sign</button>
  </fieldset>
</form>

// example/src/components/Form.tsx
import React, { FormEventHandler } from "react";
import Big from "big.js";
import { AccountInfo } from "near-wallet-selector/lib/esm/wallets/Wallet";

interface FormProps {
  account: AccountInfo;
  onSubmit: FormEventHandler;
}

const Form: React.FC<FormProps> = ({ account, onSubmit }) => {
  return (
    <form onSubmit={onSubmit}>
      <fieldset id="fieldset">
        <p>Sign the guest book, {account.accountId}!</p>
        <p className="highlight">
          <label htmlFor="message">Message:</label>
          <input autoComplete="off" autoFocus id="message" required />
        </p>
        <p>
          <label htmlFor="donation">Donation (optional):</label>
          <input
            autoComplete="off"
            defaultValue={"0"}
            id="donation"
            max={Big(account.balance)
              .div(10 ** 24)
              .toString()}
            min="0"
            step="0.01"
            type="number"
          />
          <span title="NEAR Tokens">Ⓝ</span>
        </p>
        <button type="submit">Sign</button>
      </fieldset>
    </form>
  );
};

export default Form;
