// examples/vue/src/components/Messages.vue
<script setup lang="ts">
import { Message } from "../interfaces";

defineProps<{
  messages: Array<Message>;
}>()
</script>

<template>
  <h2>Messages</h2>
  <!-- format as cards, add timestamp -->
  <p v-for="message in messages" class="{{ message.premium ? 'is-premium' : '' }}">
    <strong>{{ message.sender }}</strong>:<br />
    {{ message.text }}
  </p>
</template>

// examples/react/src/components/Messages.tsx
import React from "react";
import type { Message } from "../interfaces";

interface MessagesProps {
  messages: Array<Message>;
}

const Messages: React.FC<MessagesProps> = ({ messages }) => {
  return (
    <>
      <h2>Messages</h2>
      {messages.map((message, i) => (
        // TODO: format as cards, add timestamp
        <p key={i} className={message.premium ? "is-premium" : ""}>
          <strong>{message.sender}</strong>:<br />
          {message.text}
        </p>
      ))}
    </>
  );
};

export default Messages;
